### ISSUE TITLE
Broken XML handling if REFNR contains something else than text

### ISSUE THREAD

**Issue by maciejjan** [hsci-r/runoregi#50]
For example [searching for "tuli"](https://runoregi.fi/search?q=tuli) breaks with the following stack trace:
```
[2024-09-11 00:10:42,240] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/home/local/janicki/venv/filter/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/local/janicki/venv/filter/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/local/janicki/venv/filter/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/local/janicki/venv/filter/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/janicki/projects/hsci-r/filter-runoregi/wsgi.py", line 137, in show_search
    result = view.search.render(**args)
  File "/home/janicki/projects/hsci-r/filter-runoregi/data/logging.py", line 58, in exec_profiled_fun
    result = fun(*args, **kwargs)
  File "/home/janicki/projects/hsci-r/filter-runoregi/view/search.py", line 48, in render
    r_verses_and_inline = search_verses(db, args['q'])
  File "/home/janicki/projects/hsci-r/filter-runoregi/data/search.py", line 42, in search_verses
    result = [(nro, pos, vtype, highlight(kwd, render_xml(text))) \
  File "/home/janicki/projects/hsci-r/filter-runoregi/data/search.py", line 42, in <listcomp>
    result = [(nro, pos, vtype, highlight(kwd, render_xml(text))) \
  File "/home/janicki/projects/hsci-r/filter-runoregi/utils.py", line 86, in render_xml
    return render_xml_node(node, ref_dict)
  File "/home/janicki/projects/hsci-r/filter-runoregi/utils.py", line 64, in render_xml_node
    for refnr in c.text.split(','):
AttributeError: 'NoneType' object has no attribute 'split'
```

because of this verse:
```
+---------+------+--------------------------------------------------------+
| v_id    | type | text                                                   |
+---------+------+--------------------------------------------------------+
| 1892434 | V    | Tuli s<U>eti</U><REFNR><U>1</U></REFNR> pühapäeva,     |
+---------+------+--------------------------------------------------------+
```

where inside `<REFNR>` there is something else than just numbers.

**Comment by maciejjan** [comment]
Fixed (probably in c2208f9)
